### ISSUE TITLE
intersection of linestring and polygen are wrong in some situations

### ISSUE THREAD

**Issue by hehaha** [pygeos/pygeos#349] opened 2021-05-18 06:49 UTC
```python
# # -*- coding: utf-8 -*-
from pygeos import set_operations
from pygeos import linestrings
from pygeos import polygons
import numpy as np

if __name__ == '__main__':
    area = np.array([[1240, 8], [70, 30], [70, 704], [1250, 689], [1240, 8]])
    area = polygons(area)

    edge1 = linestrings(np.array([[600, 117.1], [635, 117.1]]))
    intersection = set_operations.intersection(area, edge1)
    print(area, edge1, intersection)

    edge2 = linestrings(np.array([[600, 116], [635, 117.1]]))
    intersection = set_operations.intersection(area, edge2)
    print(area, edge2, intersection)
```

it works correctly in version 0.8.

**Comment by jorisvandenbossche** [comment] 2021-05-18 09:54
@hehaha can you explain what exactly is wrong? For example, show the output you obtain, and clarify what your expected output would be instead. 

(I don't see any difference in output between version 0.8 and pygeos master)

**Comment by caspervdw** [comment] 2021-05-18 10:33
Please refrain from using all-capital words. On the internet, it is analogous to shouting. I edited your issue title for you.

**Comment by hehaha** [comment] 2021-05-19 03:09
> @hehaha can you explain what exactly is wrong? For example, show the output you obtain, and clarify what your expected output would be instead.
> 
> (I don't see any difference in output between version 0.8 and pygeos master)

**Comment by hehaha** [comment] 2021-05-19 03:14
I'm sorry about my expression, I'm not mean to be rude. I do don't know this capital rule. Sorry about that. 

As this problem, in 0.9 the output  is:
```
POLYGON ((1.24e+03 8, 70 30, 70 704, 1.25e+03 689, 1.24e+03 8)) LINESTRING (600 117, 635 117) LINESTRING EMPTY
POLYGON ((1.24e+03 8, 70 30, 70 704, 1.25e+03 689, 1.24e+03 8)) LINESTRING (600 116, 635 117) LINESTRING (600 116, 635 117)
```
In 0.8, the output is:
```
POLYGON ((1.24e+03 8, 70 30, 70 704, 1.25e+03 689, 1.24e+03 8)) LINESTRING (600 117, 635 117) LINESTRING (600 117, 635 117)
POLYGON ((1.24e+03 8, 70 30, 70 704, 1.25e+03 689, 1.24e+03 8)) LINESTRING (600 116, 635 117) LINESTRING (600 116, 635 117)
```
And the weird thing is that intersection is wrong when I input a linestring with same x. Like (600 117, 635 117), same x as 117.

**Comment by jorisvandenbossche** [comment] 2021-05-19 07:28
@hehaha could you show the result of `import pygeos; pygeos.geos_version` in both cases? This might be an issue in the underlying GEOS library.

**Comment by caspervdw** [comment] 2021-05-19 07:28
I am unable to reproduce this on versions 0.8, 0.9 and 0.10 (both with a self-built one with GEOS 3.8.0 and with the binary wheel on linux)

**Comment by hehaha** [comment] 2021-05-19 08:09
> import pygeos; pygeos.geos_version

I run ``` python -c "import pygeos; print(pygeos.geos_version)" ``` and got
```(3, 8, 1)``` in 0.8 and got ```(3, 9, 0)``` in 0.9

**Comment by jorisvandenbossche** [comment] 2021-05-19 08:20
There were some known bugs for overlays with lines in 3.9.0, that were fixed in 3.9.1. 

Creating an environment with GEOS 3.9.1, I can indeed reproduce it:

```
>>> print(area, edge1, intersection)
POLYGON ((1.24e+03 8, 70 30, 70 704, 1.25e+03 689, 1.24e+03 8)) LINESTRING (600 117, 635 117) LINESTRING EMPTY
>>> pygeos.geos_version
(3, 9, 0)
```

But so to fix it you can upgrade GEOS to 3.9.1:

```
>>> print(area, edge1, intersection)
POLYGON ((1.24e+03 8, 70 30, 70 704, 1.25e+03 689, 1.24e+03 8)) LINESTRING (600 117, 635 117) LINESTRING (600 117, 635 117)
>>> pygeos.geos_version
(3, 9, 1)
```

**Comment by hehaha** [comment] 2021-05-19 08:20
I installed pygeos by pip from a private pypi mirrors service which built by my company.  And I tried to install from official pypi source.  From official source I got (3.9.1) in 0.8 and (3.9.0) in 0.9. May be it's a issue in GEOS 3.9.0.

**Comment by hehaha** [comment] 2021-05-19 08:27
Now I solve this problem by downgrade pygeos to 0.8 in my project. It's would be better to update a new 0.9 package in official pypi.

**Comment by jorisvandenbossche** [comment] 2021-05-19 08:33
pygeos 0.10 was just released yesterday, and the wheels are built with GEOS 3.9.1. So you should be able to update to that.

**Comment by caspervdw** [comment] 2021-05-19 14:59
I think this solves the issue. Please reopen if necessary @hehaha .

**Closed by caspervdw** 2021-05-19 14:59 UTC
