### ISSUE TITLE
Does pygeos support sjoin like geopandas between two dataframe?

### ISSUE THREAD

**Issue by CNFeffery** [pygeos/pygeos#81] opened 2019-11-27 09:50 UTC

**Comment by jorisvandenbossche** [comment] 2019-11-27 10:29
@CNFeffery Thanks for the question! 
Currently it does not support that, but there are plans to add it, see https://github.com/pygeos/pygeos/issues/52 (so closing this issue as a duplicate of that one).

But note it will never support this between dataframes, only on arrays with geometries (but, geopandas can then make use of this to implement the version on dataframes)

**Closed by jorisvandenbossche** 2019-11-27 10:29 UTC
