### ISSUE TITLE
STRtree segfault with empty geometries

### ISSUE THREAD

**Issue by adriangb** [pygeos/pygeos#146] opened 2020-05-19 16:09 UTC
Hi folks,

We observed a segfault in STRtree within the geopandas CI. See run [here](https://travis-ci.org/github/adriangb/geopandas/jobs/688060320). Setting empty geometries to `None` before building the tree resolved the issue.

Strangely, the issue seems to only happen with `Pandas == 0.24`, so it might not be pygeos' fault, but I'm going to report it here because the segfault happens within pygeos.

I was not able to reproduce this locally using the latest Python 3.6 and Pandas == 0.24, so it might also be related to the specific Python binary or version Travis uses (I think it's not the latest).

If someone does decide to look into this, let me know if there is anything you need from me.

**Comment by brendan-ward** [comment] 2020-05-19 18:59
#147 reproduces the segfaults on Python <= 3.6

**Comment by adriangb** [comment] 2020-05-19 19:01
Wow that was quick! I'm impressed you were able to track it down so quickly, I thought it would be complicated.

**Comment by jorisvandenbossche** [comment] 2020-05-19 19:21
> #147 reproduces the segfaults on Python <= 3.6

Or it might be GEOS <= 3.6 ? (the python / GEOS versions are accidentaly all "aligned" ;))

> Strangely, the issue seems to only happen with Pandas == 0.24, so it might not be pygeos' fault, but I'm going to report it here because the segfault happens within pygeos.

That's also the only build on pandas CI that uses GEOS 3.6, the others are at GEOS 3.7 or above, I think

**Comment by brendan-ward** [comment] 2020-05-19 19:23
This happened to Shapely too: https://github.com/Toblerity/Shapely/issues/345

It looks like this was fixed in GEOS > 3.6.  (since we're not seeing it in the test matrix after that)

I think the fix here is to simply not add empty geometries to the tree.  We'll still keep them in `.geometries` and preserve their indexes.

**Comment by adriangb** [comment] 2020-05-19 19:30
The GEOS version being the issue sounds a lot more likely than the Pandas version, thank you for pointing that out.

**Comment by adriangb** [comment] 2020-05-19 19:48
@brendan-ward bringing up the tree size thing here as well, since it's related to the segfault: if we aren't even adding empty geometries to the tree, shouldn't `len(tree)` _not_ count them? I would expect `len(tree)` to have a concrete meaning, ex: number of leaves.

**Comment by brendan-ward** [comment] 2020-05-19 21:47
Unfortunately, that approach just runs into another segfault: if the tree is empty but count > 0, we attempt to query the tree and immediately fail (because the tree is not initialized with any geometries).  If we didn't increment the count for empty geometries, this would work correctly.

Ugh, empty geometries...

GEOS now ignores empty geometries on insert and correctly handles empty / uninitialized trees on query.

I'm not sure what the right thing to do is here.  Regardless of the segfaults, having empty geometries in the (GEOS) tree does not feel useful: they should never be returned for any query.  

It does seem like the length of `geometries` and `count` should be the same value.

Right now, the way `geometries` is implemented on the tree, you only get back an array of non-`None` entries from the original array you pass in to construct the index (which means it is not a cache for your inputs).  These are used internally for testing predicates, and presumably could be used later to return geometries at a given index based on a query operation.  But since query will never return their indices, you'll never need to fetch them out that way.  Keeping them seems questionable.

@jorisvandenbossche what are your thoughts on dropping empty geometries during indexing, such that `geometries` only includes non-empty geometries (i.e., only those that are ever valid to test for predicates or return given indexes from query), and `count` thus becomes the count of non-empty geometries?

**Comment by brendan-ward** [comment] 2020-05-19 22:05
Sorry for the confusion above - I was conflating the two different arrays we keep of the geometry objects.
`geometries` is an ndarray of the original geometries; indexes into this is always valid.

`_geoms` is the vector at the C level of the geometries added to the tree, used only for predicate tests.

Based on this, I think so long as there isn't a good reason to return at count of all non-`None` geometries originally passed in, that we can instead simply omit empty geometries from the tree and count.

**Comment by adriangb** [comment] 2020-05-19 22:28
I'm +1 on that approach. `geometries` is an exact copy of the input to build the tree. `_geoms` can have the None/empty/invalid/etc. geometries set to a single empty type or omitted altogether, as long as the indexing is maintained it doesn't matter.

**Comment by caspervdw** [comment] 2020-07-23 18:54
@brendan-ward  Do you know if this has been solved yet?

**Comment by brendan-ward** [comment] 2020-07-23 21:50
This was resolved by #147; apologies for not closing this at the same time!

**Closed by brendan-ward** 2020-07-23 21:50 UTC
