### ISSUE TITLE
from_shapely failing with shapely==1.8.3

### ISSUE THREAD

**Issue by akursar** [pygeos/pygeos#456] opened 2022-08-17 19:55 UTC
Using `pygeos==0.12.0`, the following test passes on `shapely==1.8.2`, but fails on `shapely==1.8.3`:

```
from pygeos.io import from_shapely, to_shapely
from shapely.geometry import Point


def test_to_from_shapely():
    point = Point(1, 2)
    pygeos_point = from_shapely(point)
    shapely_point = to_shapely(pygeos_point)
    assert shapely_point.x == 1
    assert shapely_point.y == 2
```

with

```
>           return lib.from_shapely(arr, **kwargs)
E           TypeError: Expected int for the __geom__ attribute, got LP_GEOSGeom_t
```

**Comment by akursar** [comment] 2022-08-17 19:59
Failures persist when i set `pygeos.io.shapely_compatible = False`

**Comment by jorisvandenbossche** [comment] 2022-08-17 20:10
Yes, thanks to the report. I was just looking into this because it is essentially the same problem as https://github.com/geopandas/geopandas/issues/2531 and https://github.com/shapely/shapely/issues/1485.

This is a regression in 1.8.3, and will be fixed in a quick shapely 1.8.4

**Comment by akursar** [comment] 2022-08-17 20:21
Thanks! I saw https://github.com/pygeos/pygeos/commit/06239bbe25c3edf2cda292e3103928bf8ebdee92 and thought that was related, but this also failed for me with pygeos's master branch.

**Comment by jorisvandenbossche** [comment] 2022-08-17 20:26
That commit is to fix compat with shapely 2.0, while the current regression is for 1.8.3 (and the 1.8 and 2.0 branches are completely different in shapely)

**Comment by jorisvandenbossche** [comment] 2022-08-17 20:39
(let's keep this open just a bit longer (until 1.8.4 is out), in case people are looking here to report the same issue)

**Comment by caspervdw** [comment] 2022-12-11 07:59
Closing as shapely 1.8.4 (and 1.8.5) is out

**Closed by caspervdw** 2022-12-11 07:59 UTC
