### ISSUE TITLE
[Feature request] Make STRtree serializable

### ISSUE THREAD

**Issue by carlosg-m** [pygeos/pygeos#391] opened 2021-09-15 13:30 UTC
Pygeos STRtree is to my knowledge the most relevant and fast implementation of a R-tree spatial index in Python, and it is already the backend of GeoPandas.

Similarly to Scikit-learn's KD-Tree or Ball-Tree, it would be extremely useful being able to pickle or serialize the STRtree index as fast as possible. 

This would allow for some Big Data use cases, using Dask or Spark, to distribute or parallelize the querying process between dataset partitions. 

Example from Scikit-learn documentation below:
```
tree = KDTree(X, leaf_size=2)        
s = pickle.dumps(tree)                     
tree_copy = pickle.loads(s)
```

**Comment by jorisvandenbossche** [comment] 2021-09-15 13:34
Will close as a duplicate of https://github.com/pygeos/pygeos/issues/274, we can continue the discussion there. 

In general, it's GEOS that will need to support serializing the tree (as long as that doesn't exist, the only thing we can do in pygeos is to "fake" serialization while pickling by storing the original geometries and recreating the tree from those when unpickling). I think it would certainly be interesting to bring this up to GEOS.

**Closed by jorisvandenbossche** 2021-09-15 13:34 UTC
