### ISSUE TITLE
pip install pygeos with pypy3.7 leads to faillure

### ISSUE THREAD

**Issue by Aniwax** [pygeos/pygeos#358] opened 2021-06-03 15:27 UTC
Hi team,

I am trying to install `pygeos`with `pypy3 -m pip install`, but it leads to build failure.
```
PS C:\Users\aniwax\Documents\GitHub\ibrus_new_design> pypy3 -m pip install pygeos                                       Collecting pygeos
  Using cached pygeos-0.10.tar.gz (106 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13 in c:\users\aniwax\pypy3.7-v7.3.5-win64\pypy3.7-v7.3.5-win64\site-packages (from pygeos) (1.20.2)
Building wheels for collected packages: pygeos
  Building wheel for pygeos (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\aniwax\pypy3.7-v7.3.5-win64\pypy3.7-v7.3.5-win64\pypy3.exe' 'C:\Users\aniwax\pypy3.7-v7.3.5-win64\pypy3.7-v7.3.5-win64\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\aniwax\AppData\Local\Temp\tmpts3tl1pm'
       cwd: C:\Users\aniwax\AppData\Local\Temp\pip-install-98ehg0ai\pygeos
  Complete output (48 lines):
  Could not find geos-config executable. Either append the path to geos-config to PATH or manually provide the include_dirs, library_dirs, libraries and other link args for compiling against a GEOS version >=3.5.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pygeos
  copying pygeos\constructive.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\coordinates.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\creation.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\decorators.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\enum.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\geometry.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\io.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\linear.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\measurement.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\predicates.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\set_operations.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\strtree.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\_version.py -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\__init__.py -> build\lib.win-amd64-3.7\pygeos
  running egg_info
  writing pygeos.egg-info\PKG-INFO
  writing dependency_links to pygeos.egg-info\dependency_links.txt
  writing requirements to pygeos.egg-info\requires.txt
  writing top-level names to pygeos.egg-info\top_level.txt
  reading manifest file 'pygeos.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'pygeos.egg-info\SOURCES.txt'
  copying pygeos\_geometry.c -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\_geometry.pyx -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\_geos.c -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\_geos.pxd -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\_geos.pyx -> build\lib.win-amd64-3.7\pygeos
  copying pygeos\_pygeos_api.pxd -> build\lib.win-amd64-3.7\pygeos
  UPDATING build\lib.win-amd64-3.7\pygeos/_version.py
  set build\lib.win-amd64-3.7\pygeos/_version.py to '0.10'
  running build_ext
  building 'pygeos.lib' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\aniwax\pypy3.7-v7.3.5-win64\pypy3.7-v7.3.5-win64\include -IC:\Users\aniwax\AppData\Local\Temp\pip-build-env-5f6wb7j8\overlay\site-packages\numpy\core\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcsrc/c_api.c /Fobuild\temp.win-amd64-3.7\Release\src/c_api.obj
  c_api.c
  C:\Users\aniwax\AppData\Local\Temp\pip-install-98ehg0ai\pygeos\src\geos.h(12): warning C4068: unknown pragma 'GCC'
  C:\Users\aniwax\AppData\Local\Temp\pip-install-98ehg0ai\pygeos\src\geos.h(13): warning C4068: unknown pragma 'GCC'
  C:\Users\aniwax\AppData\Local\Temp\pip-install-98ehg0ai\pygeos\src\geos.h(14): fatal error C1083: Cannot open include file: 'geos_c.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pygeos
Failed to build pygeos
ERROR: Could not build wheels for pygeos which use PEP 517 and cannot be installed directly
```

I know in general, you guys suggest to use conda instead of pip, but since all my other dependencies are installed with pip, it's just easier to keep it in the same place.

It would be great if you guys can provide a `.whl` file for installing pygeos on pypy. Or anything that works with pip on pypy. Thanks a lot!

-----------------------
Operating System: Windows 64, amd
Pypy versions:  [`PyPy 7.3.5 with MSC v.1927 64 bit (AMD64)`],  [`PyPy 7.3.4 with MSC v.1927 64 bit (AMD64)`] on win32

**Comment by caspervdw** [comment] 2021-06-05 08:52
Hi @Aniwax,

Compiling from source on windows can be hard, because GEOS is not found automatically. You’ll have to download and install GEOS from https://trac.osgeo.org/osgeo4w/ and then  set GEOS_INCLUDE_PATH and GEOS_LIBRARY_PATH environment variables accordingly. 

I am not sure what directories will be used, but you’ll have to make sure that the library path contains the .dll and the include path the .h files.

I hope that works!
And pypy wheels are indeed missing. Let’s keep this issue open and try to arrange that.

**Comment by caspervdw** [comment] 2021-09-07 11:36
Duplicate of #371 - closing. @Aniwax please feel free to reopen if you have questions or updates on building on Pypy.

**Closed by caspervdw** 2021-09-07 11:36 UTC
